// Test file for client-reported false positives
// These are auto-generated type names that should NOT be flagged as secrets

// From Image 1 - JSON/GraphQL schema type name
export type OkQueryCollectionResponseOfServicePlanSelectorQueryRequestAndServicePlanSelectorQueryResponseData = {
  __typename?: 'OkQueryCollectionResponseOfServicePlanSelectorQueryRequestAndServicePlanSelectorQueryResponseData';
  data?: unknown;
};

// From Image 2 - TypeScript type definitions
export type OkQueryCollectionResponseOfSubscriptionPackagesQueryAndSubscriptionPackagesResponse = {
  __typename?: 'OkQueryCollectionResponseOfSubscriptionPackagesQueryAndSubscriptionPackagesResponse';
  /** A collection of human-readable explanation of errors encountered. Empty if no errors occured. */
  detail?: Maybe<Scalars['String']['output']>;
  /** A collection of human-readable explanation of errors encountered. Empty if no errors occured. */
  errors?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  /** False if request failed */
  isFailure?: Maybe<Scalars['Boolean']['output']>;
  /** True if request succeeded */
  isSuccess?: Maybe<Scalars['Boolean']['output']>;
  /** The Web API request. */
  request?: Maybe<SubscriptionPackagesQuery>;
  result?: Maybe<Array<Maybe<SubscriptionPackagesResponse>>>;
  /** The HTTP status code([RFC7231], Section 6) generated by the origin server for this occurrence of the problem. */
  status?: Maybe<Scalars['Int']['output']>;
  /** Http status code description */
  statusDetails?: Maybe<Scalars['String']['output']>;
  /** A short, human-readable summary of the problem type. It SHOULD NOT change from occurrence to occurrence of the problem, except for purposes of localization(e.g., using proactive content */
  title?: Maybe<Scalars['String']['output']>;
  /** A URI reference [RFC3986] that identifies the problem type. This specification encourages that, when dereferenced, it provide human-readable documentation for the problem type (e.g., usi */
  type?: Maybe<Scalars['String']['output']>;
};

export type OkQueryResponseOfServicePlanQueryRequestAndServicePlanQueryResponseData = {
  __typename?: 'OkQueryResponseOfServicePlanQueryRequestAndServicePlanQueryResponseData';
  data?: unknown;
};

// Helper types for compilation
type Maybe<T> = T | null | undefined;
type Scalars = {
  String: { output: string };
  Boolean: { output: boolean };
  Int: { output: number };
};
type SubscriptionPackagesQuery = unknown;
type SubscriptionPackagesResponse = unknown;
